CREATE TABLE PAIS (ID_PAIS NUMBER PRIMARY KEY,
                   NOME_PAIS VARCHAR2(30)NOT NULL);
CREATE TABLE ESTADO (ID_ESTADO NUMBER PRIMARY KEY,
                   NOME_ESTADO VARCHAR2(30)NOT NULL,
                   ID_PAIS NUMBER);
ALTER TABLE ESTADO ADD CONSTRAINT FK_ESTADO FOREIGN KEY
(ID_PAIS) REFERENCES PAIS (ID_PAIS);

SELECT * FROM PAIS;

SELECT * FROM ESTADO;

DROP TABLE PAIS;

INSERT INTO ESTADO VALUES (1,'SÃO PAULO',1);
INSERT INTO ESTADO VALUES (2,'RIO DE JANEIRO',1);

INSERT INTO PAIS VALUES (1,'BRASIL')
